### ISSUE TITLE
Some hints that was found when working on examples for Glavin001/atom-beautify

### ISSUE THREAD

**Issue by Eiji7** [lexmag/elixir-style-guide#19]
1. @lexmag: commented about: [true-in-cond](https://github.com/lexmag/elixir-style-guide#true-in-cond) rule in Glavin001/atom-beautify#1421.
> Now I see, the rule wasn't clear, it meant the we should always use true and not any other atom since cond allows any:
> ```elixir
> cond do
>   :any -> :ok
> end
> ```
2. When parsing `README.md` I found unneeded (?) link in [pipeline-operator](https://github.com/lexmag/elixir-style-guide/blob/master/README.md#pipeline-operator). As I can see all other rules have links **only** at end of first paragraph for rule (list element in list for header level 3 - h3 - element):
> ```html
> <a name="needless-pipeline"></a>
> ```

**Comment by lexmag** [comment]
Closed via #20.
