### ISSUE TITLE
Add more examples and "Bad" versions of examples to rules

### ISSUE THREAD

**Issue by Eiji7** [lexmag/elixir-style-guide#21]
Lots of rules don't have a sample code and most of rules also don't have a "Bad" version of example.

Some beginners do not know perfectly English (how translation tools work I do not need to explain - there are also not perfect) and other developers (like me) can misunderstand some rules. To avoid this I suggest to add/extend examples.

When I created an examples for atom-beautify I added more examples and all have "Bad version" (original) and "Good" version (expected). There shows why this rules are important and there were already reviewed by @lexmag, so they do not need lots of edits to add them here.

Here is my PR: Glavin001/atom-beautify#1421

Do you interested in this? What do you think about it? Can I take it and add PR based on examples from atom-beautify?

**Comment by whatyouhide** [comment]
I added a lot of "Bad" examples recently, I am not sure this issue is still valid. If you still find that some rules could benefit from more "bad" examples, feel free to open issues or PRs about them :) Thanks @Eiji7! 💟
