### ISSUE TITLE
Parenthesis around anonymous function arguments

### ISSUE THREAD

**Issue by ericmj** [lexmag/elixir-style-guide#23]
Good or bad?

**Comment by christopheradams** [comment]
I favor them. But neither good nor bad, just a preference. Elixir allows a lot of unnecessary parens, but if it really looks like a function, better to enclose the arguments with them.

**Comment by whatyouhide** [comment]
Me (and @lexmag, I'm pretty sure) favor them, but @josevalim is quite strongly against them IIRC so we've been holding this point off for a while. My personal opinion is that we should align with Elixir when/if we can, so lately I try not to use them in the code and see how it goes.

FWIW, my point in favor of parens is that reading a function call that takes an anonymous `fn` can be pretty tricky otherwise:

```elixir
my_fun(arg1, {arg2, arg3}, %{43 => 312, 23 => 32}, fn {acc1, foo}, {acc2, bar} ->
```

The example above is of course deliberately complex but parens in the `fn` make me distinguish the arguments to `my_fun` and the arguments to `fn` quite more clearly.

@ericmj what's your stance?

**Comment by josevalim** [comment]
`fn` and `->` is enough to distinguish them. If you have too many arguments in a single line, you can break the fn arguments into the next line.

**Comment by whatyouhide** [comment]
As you can see, @josevalim is quite diplomatic 😄 Just kidding, as I said, I prefer parens but prefer even more to be as aligned as we can with Elixir. @lexmag are you ready to surrender? :P

**Comment by ericmj** [comment]
I personally prefer no parenthesis so my vote is for avoiding them.

Not sure how important it is follow elixir-lang conventions though, if this would be the only difference then it would be a shame to introduce it. Are there any other things in this style guide that differs from convention in elixir-lang?

**Comment by whatyouhide** [comment]
@ericmj not a lot of "strong" ones. Off the top of my head, we tend to have `def foo do` in Elixir but advise `def foo() do` here (but this convention is not strong in Elixir itself), and I can't recall any other strong ones. Me and @lexmag (sorry for speaking for you Aleksei) are quite strongly against `& &1 == ...` (no parens for `&`) but José is quite in favor, but we don't have this rule in this style guide.

It's not terribly important to be aligned to elixir-lang, but I consider it a strong pro of this style guide. This would be one of the very few differences, so if you and José are for no parens I think we should advise no parens and call it a day. Better to have consistent code IMO.

**Comment by josevalim** [comment]
`& &1 == ...` is Elixir's best feature.

**Comment by whatyouhide** [comment]
@josevalim 

![giphy](https://cloud.githubusercontent.com/assets/3890250/23300535/3872f97e-fa86-11e6-9a1a-c35b750d43d6.gif)

Also, all of http://giphy.com/search/disappointed 😄

**Comment by lexmag** [comment]
All what @whatyouhide said about my personal preferences on style is right.
Also Andrea is correct on the differences with elixir-lang: only `def foo() do` I can recall (I'm happy that we stopped [aligning everything](https://github.com/lexmag/elixir-style-guide#expression-group-alignment), it was another difference).
I don't feel very strong on making this guide cemented to elixir-lang style, however it would be great to be close as much as we can.
Anonymous functions with more than one argument begging of getting them parenthesis. 😁

> @lexmag are you ready to surrender? :P

I had minor hope (but still hope) that @ericmj will join the camp of parenthesis-lovers, so we'll be fine to have one more difference in the guide.
But for now we have "split forces" 2/2 (though I'm quite sure @fishcakez likes parenthesis).
Maybe we can "trade" `def foo() do` for not having parenthesis around `fn`? 😄
Shall we let it be wild west of parenthesis?

**Comment by lexmag** [comment]
@josevalim the best feature of GitHub is that you can react on your own comments. :stuck_out_tongue_closed_eyes:

![screen shot 2017-02-24 at 11 55 07](https://cloud.githubusercontent.com/assets/248290/23300929/1d71db3e-fa88-11e6-8b21-a8fc14ec938d.png)

**Comment by chrismccord** [comment]
Bad. I see no reason to use parens on anon args, as they add nothing in clarity. I say this as someone who now is in the parens camp on all null arity calls, no exceptions. In the case of anon args, I see parens only as noise.

**Comment by whatyouhide** [comment]
The no-parens cartel grows bigger!

**Comment by michalmuskala** [comment]
Why did I not know this repo existed with such discussions? 😆 

I prefer no parens as well.

**Comment by ngw** [comment]
No parens!

**Comment by lexmag** [comment]
It seems one tweet was enough to see that we perhaps should not require parenthesis. 😂

**Comment by whatyouhide** [comment]
It's decided: no parens. I will prepare a PR today.

**Comment by josevalim** [comment]
> That's one small step for man, one giant leap for mankind.
