### ISSUE TITLE
Elixir Style reference card format

### ISSUE THREAD

**Issue by milmazz** [lexmag/elixir-style-guide#27]
I was a little bit bored and I made this [reference card](https://github.com/lexmag/elixir-style-guide/files/963000/elixir-style-refcard.pdf) as an adaptation of the *Elixir Style Guide*. It was also a good way to remember a few things from the style guide :)

I already printed and pinned this refcard and looks good on my desk, if you agree I plan to publish the source code (LaTeX) in https://github.com/milmazz/elixir-style-refcard under the same license (CC BY 4.0)

@lexmag Please let me know what do you think? Do you have any suggestion?

**Comment by lexmag** [comment]
@milmazz this is fabulous! 💛
Please do publish it, and we surely should link to it.
I will check card more carefully tomorrow, and then will open issues with suggestions (if any) in your repository.

**Comment by milmazz** [comment]
@lexmag Done! 

http://milmazz.uno/elixir-style-refcard/
