### ISSUE TITLE
Code style linter

### ISSUE THREAD

**Issue by lexmag** [lexmag/elixir-style-guide#3]

**Comment by Eiji7** [comment]
**Note**: if someone is interested
From 15th December I will start work at **original** => **expected** examples that are based on this style guide for [atom-beautify](https://github.com/Glavin001/atom-beautify) project.
Hope that will help you.

**Comment by lexmag** [comment]
Wonderful! Thank you @Eiji7! 💛

**Comment by Eiji7** [comment]
@lexmag: I created PR Glavin001/atom-beautify#1421. Do you have a time to look at my examples? All your work is in `@doc` and info about source and license in `@moduledoc` (+ README.md). I added some changes to allow compile all files without error(s) and/or warning(s) (for exxample I need escape some docs or I was need to declare variables used in your examples).

**Comment by lexmag** [comment]
@Eiji7 I have just reviewed that PR.

**Comment by whatyouhide** [comment]
@lexmag can this be closed off given the GSoC project and the birth of a couple of actual formatters?

**Comment by lexmag** [comment]
@whatyouhide definitely.
