### ISSUE TITLE
Zero arity fn -> spacing

### ISSUE THREAD

**Issue by lpil** [lexmag/elixir-style-guide#30]
Which is correct?

```elixir
# 1
fn-> :ok end

# 2
fn -> :ok end
```

Related to: https://github.com/lpil/exfmt/issues/13

**Comment by lexmag** [comment]
I believe we want space in-between. @whatyouhide thoughts?

**Comment by whatyouhide** [comment]
Absolutely space in-between. @lpil feel free to submit a PR if you think there's enough debate in the community for this (I think we don't have it as a rule because `fn->` is not common at all, at least in the code I've seen?).

**Comment by lpil** [comment]
For some reason I've adopted it thinking it was the common style. Not sure where I picked that up from. Thanks all :)

I think it's worth adding, just to be explicit.

**Comment by whatyouhide** [comment]
@lpil PR welcome :)

**Comment by whatyouhide** [comment]
Closed in https://github.com/lexmag/elixir-style-guide/commit/611cac31c4b83e770cfb542da670f7b5c8514ea2.
