### ISSUE TITLE
Question about multiline expression assignment

### ISSUE THREAD

**Issue by uohzxela** [lexmag/elixir-style-guide#32]
With reference to this [rule](https://github.com/lexmag/elixir-style-guide#multi-line-expr-assignment), we have an example as follows:

```
{found, not_found} =
  Enum.map(files, &Path.expand(&1, path))
  |> Enum.partition(&File.exists?/1)
```

My formatter output:

```
{found, not_found} = Enum.map(files, &(Path.expand(&1, path)))
|> Enum.partition(&(File.exists?() / 1)) 
```
Is it stylistically correct?

Here's another example with binary operator:

```
result =
  op_to_string(left, fun, :::, :left) <>
  "::" <>
  bitmods_to_string(right, fun, :::, :right)
```

```
result = op_to_string(left, fun, :::, :left) <>
"::" <>
bitmods_to_string(right, fun, :::, :right)
```

**Comment by binaryseed** [comment]
I just made a suggestion about the formatting in this case: https://github.com/lexmag/elixir-style-guide/pull/33

**Comment by whatyouhide** [comment]
```elixir
{found, not_found} = Enum.map(files, &(Path.expand(&1, path)))
|> Enum.partition(&(File.exists?() / 1)) 
```

> Is it stylistically correct?

Nope. The second formatted result isn't stylistically correct either. I would say the rule you refer to only applies to things that take a block or a `fn` (something that ends in `end`), for example

```elixir
mapped = Enum.map(list, fn elem ->
  # ...
end)
```

can be considered okay. @binaryseed I am personally not sure yet about #33 but I will discuss it with @lexmag.

In the meantime, closing this issue. Let me know if you still need clarification @uohzxela 👍
