### ISSUE TITLE
How to split guard clause attached to a case condition?

### ISSUE THREAD

**Issue by uohzxela** [lexmag/elixir-style-guide#35]
I have this piece of code with a very long guard clause attached to a case condition:

```
case ast do
  {sym, meta1, [{fun, meta2, nil} | rest]} when sym in [:def, :defp, :defmacro, :defmacrop, :defdelegate] ->
    {sym, meta1, [{fun, meta2, []} | rest]}
  _ ->
    ast
end

```
I split it after the `when` operator with extra indentation like so:

```
case ast do
  {sym, meta1, [{fun, meta2, nil} | rest]} when
      sym in [:def, :defp, :defmacro, :defmacrop, :defdelegate] ->
    {sym, meta1, [{fun, meta2, []} | rest]}
  _ ->
    ast
end
```

Is this correct?

**Comment by whatyouhide** [comment]
I would argue that the when goes on the newline as we do for def and friends but I wouldnt know how to indent next line then, probably four spaces? Anyways worth pointing out that this is a very borderline case and better solutions here are extract list of atoms to module attr, or get rid of the case and use an helper function and match on the head of it.

**Comment by uohzxela** [comment]
Indeed, it makes sense to refactor than trying to shoehorn it to a style rule. :)

**Comment by davearonson** [comment]
Re how to indent it, I usually do _at least two_ control levels' worth for a line that _continues_ a control statement, when there's going to be another control level coming soon.  (Unless of course there's something obvious to align it with, like a function/macro name)  So, if we do both of the above suggestions plus this, we'd wind up with:
```
@defers ~w(def defp defmacro defmacrop defdelegate)a
...
case ast do
  {sym, meta1, [{fun, meta2, nil} | rest]}
      when sym in defers ->
    {sym, meta1, [{fun, meta2, []} | rest]}
  _ ->
    ast
end
```

**Comment by lexmag** [comment]
I think 2 indentation levels (4 spaces) is how I'd intent it if I were really needed to do that.
_We actually do so for Erlang code in Elixir (both for definitions and `case` clauses)._

However, I don't think we have other examples of such indentation, and as @whatyouhide pointed out, would be better if that `case` will be refactored, thus it should be fine to keep that long line (so it will constantly be creaming to its writer about refactoring). :bowtie:

**Comment by uohzxela** [comment]
@lexmag sounds good, closing this issue since the consensus leans toward refactoring instead. Thanks all! :)
