### ISSUE TITLE
Question about parenthesis on chained zero arity function calls

### ISSUE THREAD

**Issue by rgreenjr** [lexmag/elixir-style-guide#40]
Is there a standard for parenthesis on chained zero arity function calls? For example, 

```elixir
Mix.shell.info("hello")
```

versus

```elixir
Mix.shell().info("hello")
```

The style guide generally seems to prefer parenthesis for clarity, but I didn't see this particular case addressed. 

I ask because I'm working on the [exfmt](https://github.com/lpil/exfmt) project and need to implement the rules for this scenario.

Thanks!

**Comment by ericmj** [comment]
Always use parenthesis, even when chaining.

**Comment by rgreenjr** [comment]
Thanks Eric :)

**Comment by whatyouhide** [comment]
There's nothing special about "chaining". You are just calling `info/1` on the return value of `Mix.shell/0`. So you would call `Mix.shell()` with parens (as per style guide) and then call `info/1` on that.

**Comment by rgreenjr** [comment]
@whatyouhide Of course there's nothing special about "chaining". But this is a style guide, which means semantics are not the point. There are many instance where the style rules differ based solely on context. Take the parenthesis rules for zero arity functions in type declarations as one example.

**Comment by lpil** [comment]
How about in this situation? Seems when there are no arguments and the left hand side of `.` is not an alias or an atom we can't be sure which format is desired in the context of a formatter.

```elixir
map = %{a: %{b: %{c: 1}}}

map.a.b.c

map.a().b().c()
```

**Comment by ericmj** [comment]
@lpil Those are not function calls so they should not have parenthesis. Since it's impossible for a formatter to know if it's a function call or access lookup it should just leave it as-is.

**Comment by whatyouhide** [comment]
@lpil https://github.com/uohzxela/ex_format/issues/28#issuecomment-322061391

**Comment by lpil** [comment]
Looks like we're thinking along the same lines. Thanks all :)
