### ISSUE TITLE
How to split long function specs?

### ISSUE THREAD

**Issue by uohzxela** [lexmag/elixir-style-guide#44]
Let's say I have a very long function spec:

`@callback handle_call(request :: term, state :: term) :: {:ok, reply, new_state} | {:ok, reply, new_state, :hibernate} | {:remove_handler, reply}`

How do we split this?

**Comment by whatyouhide** [comment]
I do this

```elixir
@callback handle_call(request :: term, state :: term) ::
          {:ok, reply, new_state} |
          {:ok, reply, new_state, :hibernate} |
          {:remove_handler, reply}
```

**Comment by uohzxela** [comment]
Thanks @whatyouhide!

**Comment by christopheradams** [comment]
@lexmag Is this style rule for `@callback`, as well as `@spec`, deserving of mention in the guide? I'm sure it will keep coming up.
