### ISSUE TITLE
"Blocks" inside pipes

### ISSUE THREAD

**Issue by execb5** [lexmag/elixir-style-guide#48]
I don't know if calling it blocks would be the correct way, but basically I'd like to know what would be the preferred way of organizing cases, (), {} and [] inside pipes.
The situation would be something like this:

```elixir
Repo.get(App, "app_id")
|> case do
     nil -> %App{}
     app -> app
   end
|> App.changeset(%{
     id: "new_app_id",
     name: "The name of this app is something kinda long so it needs a line for that"
   })
|> Repo.insert_or_update!
```

Right now I'm using the way shown above because it makes sense to me to close it in the same indentation level of the beginning of the "block", but... it's a little bit weird and totally not clean.

**Comment by davearonson** [comment]
My preferred way would be to extract that logic into a well-named function.  I'm not a well-seasoned Elixirist yet, but at least that's the approach that has helped me make large nests of logic much more understandable in other languages, whether it be nested function calls in C or a long chain of method calls with blocks in Ruby, or whatever.

**Comment by execb5** [comment]
That's good advice, but the question still remains...
A `case` can be avoided doing that, but that's why I also added a long parameter in the example.

**Comment by davearonson** [comment]
The long param can be accommodated, and with less length, in something like:
```
|> make_id_and_name_changeset("new_app_id",
                               "some very long string that should go on its own line")
```
Still takes extra lines but at least not so many, and describes the intent somewhat so it doesn't interrupt the reader's thought about the _current_ flow of logic as much.

**Comment by RaymondLoranger** [comment]
My preference is: all lines should always be indented but minimally indented:
```elixir
Repo.get(App, "app_id")
|> case do
  nil -> %App{}
  app -> app
end
|> App.changeset(
  %{
    id: "new_app_id",
    name: "The name of this app is something kinda long " <>
      "so it needs a line for that"
  }
)
|> Repo.insert_or_update!
```

**Comment by whatyouhide** [comment]
I am closing this since the [code formatter](https://elixirforum.com/t/running-the-new-elixir-formatter/9344) now takes care of this. :)
